### ISSUE TITLE
Change license to MPLv2

### ISSUE THREAD

**Issue by c-rack** [c-rack/cidr-elixir#31]
I would like to change the license of cidr-elixir from MIT to [MPL](https://www.mozilla.org/en-US/MPL/2.0/).

According to the [C4.1 process](http://rfc.zeromq.org/spec:22), the MPL is recommended to use:

> The project SHALL use a share-alike license, such as the GPLv3 or a variant thereof (LGPL, AGPL), or the MPLv2.

@duijf would you agree to change to MPL?

**Comment by duijf** [comment]
Ehrm, don't know the implications that well. Just got back from a trip and need to catch up on some work. I'll take a look this weekend.

**Comment by c-rack** [comment]
Take your time. There is also one PR waiting in this project :-)

**Comment by duijf** [comment]
Alright, so I had a chance to look this over, I have a philosophical viewpoint to offer and also a couple of questions.

In general, I like to write software that helps developers, and their users. I think this works the best when little to no restrictions are imposed on the use of a library. Therefore I don't particularly like licenses with a virality clause that says others must release modified code under the same license. 

I have read both the license (and did the best I could to comprehend it), as well as [a summary on TL;DRLegal](https://tldrlegal.com/license/mozilla-public-license-2.0-%28mpl-2%29). As far as I know, the MPL requires developers making use of this library to publish modifications they make.

However publishing the changes is not the same as sending a PR and trying to integrate them. Others can simply put the changed sources in a tarball on their website and be compliant with the license.

In general I don't like to worry about this and let the other people make use of my code however they want. Someone that doesn't want to share and cooperate will not magically be transformed into a great open source collaborator because of the license of the project. Those that want to contribute will do so anyway.

Now, the above is my philosophical reservation with adopting the MPL. My questions:
- What is your aim with changing the license? Because it is defined in the C4.1 process or because it has its own benefits?
- If it has its own benefits; what are they?
- If it is to be compliant with C4.1; why are we following it? (I like a lot, just don't want to blindly adopt the MPL because it says in the process).

**Comment by duijf** [comment]
I hope it is clear that I don't want to shut the door on this, just wondering about the effects of the choice and whether it is the right decision.

**Comment by c-rack** [comment]
Thanks for your response. I found a very useful summary and explanation about the differences and benefits of the MPL over other licenses (including Apache):
http://www.gatsbymedia.net/development-articles/why-we-use-the-mpl

Here are the key sentences:

> Some popular licenses like Apache 2.0 are not compatible with version 2 of the GPL and even though version 3 of the GPL is compatible with Apache 2.0, version 2 of the GPL is still very popular and used for the Linux kernel and Wordpress. The MPL is compatible with Apache 2.0 and other permissive licenses by leaving their existing licenses alone.
> 
> Code under the GPL and MPL protect the copyright holder by requiring code to stay under the original copyleft license and any derivative works or "forks" must follow that license. The original copyright holder of the GPL or MPL code can change the license at any time, but the owner of a derivative work cannot change the license and is bound to it as long as the project is made available.
> 
> Permissive licenses like Apache 2.0 differ by allowing the modification and distribution of the source code without contributing modifications back to the owner or keeping the same license. An individual or company can take code under a permissive license, integrate it with their commercial application, and make money off of the code without involving the original copyright holder.

For me, the MPL seems to be the best license for open-source projects and libraries. They still can be used commercially, but improvements and modifications must be given back to the community, which is just fair. Additionally, MPL is compatible to GPLv2, which Apache is not.

So I can see only benefits and no drawbacks. What do you think?

**Comment by c-rack** [comment]
@duijf have you made any decision yet? :-)

**Comment by duijf** [comment]
Yes, sorry it took so long. Thanks for your amswer and considerations. I'm okay with the change :)
